<% title "We're sorry, but something went wrong" %>

<div id="errorExplanation", class="error-messages">
  <ul> The following error message was observed:
    <li> <%= exception.message %> </li>
  </ul>
</div>

<p>
  If you feel this is an error with Foreman itself, please open a new issue with <%= link_to "Foreman ticketing system", "http://theforeman.org/projects/foreman/issues", :rel => "external" %>,
  You would probably need to attach the
  <%= link_to_function "Full trace", toggle_div("backtrace") %> and relevant log entries.
</p>

<div id="backtrace", <%= display? %> class="alert-message block-message error">
  <em><%= exception.class %></em><br>
  <strong><%= exception.message %></strong><br>
  <%= exception.application_backtrace.join("<br>") %>
</div>
<p><%= link_to "Back", root_path %></p>
